language: cpp

env:
  matrix:
    - FUN_DEVHAXE=false
    - FUN_DEVHAXE=true

install:
 - if [ -z "$TRAVIS_OS_NAME" ]; then export TRAVIS_OS_NAME=linux; fi; # for forks that do not have multi-os enabled
 - if [ -z "$FUN_TARGET" ]; then export FUN_TARGET=$TRAVIS_OS_NAME; fi;
 - bash test/setup.sh $TRAVIS_OS_NAME $FUN_TARGET $FUN_DEVHAXE travis_retry

script:
 - bash test/test.sh $FUN_TARGET
